default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  database: fleetrider
  username: sa
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: utf8

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default